# Generated by Django 4.2.4 on 2023-08-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_salud',
            fields=[
                ('id_ES', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio_o', models.CharField(max_length=45)),
                ('indicativo_o', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('costo_t', models.IntegerField()),
                ('fk_Entidad_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entidad_salud')),
            ],
        ),
    ]
